export const ML_STAKED_LOADING = "ML_STAKED_LOADING";
export const ML_STAKED_SUCCESS = "ML_STAKED_SUCCESS";
export const ML_STAKED_ERROR = "ML_STAKED_ERROR";

// export const ML_CLAIM_SUCCESS = "ML_CLAIM_SUCCESS";
// export const ML_CLAIM_ERROR = "ML_CLAIM_ERROR";
//
// export const ML_UNSTAKE_SUCCESS = "ML_UNSTAKE_SUCCESS";
// export const ML_UNSTAKE_ERROR = "ML_UNSTAKE_ERROR";
